/* CRIANDO BANCO DE DADOS DO RESTAURANTE */
CREATE DATABASE BDRESTAURANTE
/* USANDO BANDO DE DADOS */
USE BDRESTAURANTE
/* CRIANDO AS TABELAS DO BANCO */
CREATE TABLE FUNCIONARIO(
CODIGO_FUNCIONARIO INT PRIMARY KEY IDENTITY NOT NULL,
NOME_FUNCIONARIO VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
CPF VARCHAR(20) NOT NULL,
)
CREATE TABLE GERENTE(
CODIGO_GERENTE INT PRIMARY KEY IDENTITY NOT NULL,
NOME_GERENTE VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
CPF VARCHAR(20) NOT NULL,
)
CREATE TABLE CLIENTE(
CODIGO_CLIENTE INT PRIMARY KEY IDENTITY NOT NULL,
NOME_CLIENTE VARCHAR(50),
EMAIL VARCHAR(50) NOT NULL,
CPF VARCHAR(20) NOT NULL,

)
CREATE TABLE PRODUTO(
CODIGO_PRODUTO INT PRIMARY KEY IDENTITY NOT NULL,
CODIGO_CLIENTE INT,
NOME_PRODUTO VARCHAR(50)NOT NULL,
VALOR_PRODUTO FLOAT NOT NULL,
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
)
CREATE TABLE PAGAMENTO(
CODIGO_PAGAMENTO INT PRIMARY KEY IDENTITY NOT NULL,
CODIGO_FUNCIONARIO INT,
CODIGO_PRODUTO INT,
DINHEIRO FLOAT,
CARTAO VARCHAR(20),
QUANTIDADE_PRODUTO INT,
VALOR_TOTAL FLOAT,
FOREIGN KEY(CODIGO_FUNCIONARIO) REFERENCES FUNCIONARIO(CODIGO_FUNCIONARIO),
FOREIGN KEY(CODIGO_PRODUTO) REFERENCES PRODUTO(CODIGO_PRODUTO),
)
CREATE TABLE DELIVERY(
CODIGO_DELIVERY INT PRIMARY KEY IDENTITY,
CODIGO_CLIENTE INT,
CODIGO_PEDIDO INT,
VALOR_TOTAL FLOAT,
QUANTIDADE_PRODUTO INT,
HORARIO TIME,
DATA_DELIVERY DATE,
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE),
)
CREATE TABLE RESERVA(
CODIGO_RESERVA INT PRIMARY KEY IDENTITY,
CODIGO_CLIENTE INT,
DATA_RESERVA DATE,
HORARIO TIME,
COMANDA INT,
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES  CLIENTE(CODIGO_CLIENTE),
)
CREATE TABLE TELEFONE(
CODIGO_TELEFONE INT PRIMARY KEY IDENTITY,
NUMERO_RESIDENCIAL VARCHAR(20),
NUMERO_CELULAR VARCHAR(20),
CODIGO_CLIENTE INT,
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE),
)
CREATE TABLE ENDERECO(
CODIGO_ENDERECO INT PRIMARY KEY IDENTITY,
RUA VARCHAR(50),
BAIRRO VARCHAR(50),
NUMERO VARCHAR(10),
CODIGO_CLIENTE INT,
CODIGO_DELIVERY INT,
FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE),
FOREIGN KEY    (CODIGO_DELIVERY) REFERENCES DELIVERY(CODIGO_DELIVERY),
)

CREATE TABLE USUARIO(
CODIGO_LOGIN INT PRIMARY KEY IDENTITY,
USUARIO VARCHAR(20) NOT NULL,
SENHA VARCHAR(20) NOT NULL
)

 /* 4ª CONSULTANDO AS TABELAS NO BANCO DE DADOS */
SELECT * FROM FUNCIONARIO
SELECT * FROM GERENTE
SELECT * FROM CLIENTE
SELECT * FROM PRODUTO
SELECT * FROM PAGAMENTO
SELECT * FROM RESERVA
SELECT * FROM DELIVERY
SELECT * FROM TELEFONE
SELECT * FROM ENDERECO
SELECT * FROM USUARIO
INSERT INTO USUARIO (USUARIO, SENHA) values ('raul', '123456');
drop table ENDERECO
drop table TELEFONE
drop table DELIVERY
drop table RESERVA
drop table PAGAMENTO
drop table PRODUTO
drop table CLIENTE
drop table GERENTE
drop table funcionario
drop table USUARIO








drop table USUARIO